const FORTUNE_CARDS = [
  { id: 'mundo_al_reves', nombre: 'El mundo al revés', categoria: 'Caos', desc: 'Permanente hasta la próxima fortuna: curar hace daño y el daño cura', efecto: 'swap_heal_damage' },
  { id: 'identidad_robada', nombre: 'Identidad robada', categoria: 'Caos', desc: 'Ambos jugadores intercambian todos sus stats por 5 turnos', efecto: 'swap_stats', duracion: 5 },
  { id: 'el_traidor', nombre: 'El traidor', categoria: 'Caos', desc: 'Las pasivas de ambos jugadores trabajan en contra suya por 3 turnos', efecto: 'reverse_passives', duracion: 3 },
  { id: 'velocidad_maldita', nombre: 'Velocidad maldita', categoria: 'Caos', desc: 'El jugador MÁS rápido pierde su turno por 3 turnos. El lento va primero', efecto: 'slow_fast', duracion: 3 },
  { id: 'antifuerza', nombre: 'Antifuerza', categoria: 'Caos', desc: 'Por 4 turnos, a más fuerza tengas, menos daño hacés', efecto: 'anti_strength', duracion: 4 },
  { id: 'ruleta_rusa', nombre: 'Ruleta rusa', categoria: 'Muerte', desc: 'Ambos tiran un dado en secreto. El que saque menos muere instantáneamente. Si empatan, nada pasa', efecto: 'russian_roulette' },
  { id: 'juicio_divino', nombre: 'Juicio divino', categoria: 'Muerte', desc: 'El jugador con más stats totales pierde la mitad de su HP ahora mismo', efecto: 'divine_judgment' },
  { id: 'el_elegido', nombre: 'El elegido', categoria: 'Muerte', desc: 'El jugador con menos HP recibe una TA aleatoria extremadamente poderosa permanentemente', efecto: 'chosen_one' },
  { id: 'extincion', nombre: 'Extinción', categoria: 'Muerte', desc: 'Todos los objetos equipados de ambos jugadores se destruyen para siempre', efecto: 'destruct_equipment' },
  { id: 'reset', nombre: 'Reset', categoria: 'Muerte', desc: 'Ambos jugadores vuelven al HP con el que empezaron la partida. Stats no cambian', efecto: 'reset_hp' },
  { id: 'modo_espejo', nombre: 'Modo espejo', categoria: 'Ilusion', desc: 'Por 3 turnos, cada vez que alguien recibe daño, el rival recibe exactamente lo mismo también', efecto: 'mirror_damage', duracion: 3 },
  { id: 'pacifismo_forzado', nombre: 'Pacifismo forzado', categoria: 'Ilusion', desc: 'Por 2 turnos nadie puede atacar directamente. Solo TAs, poses y descanso', efecto: 'pacifism', duracion: 2 },
  { id: 'sed_de_sangre', nombre: 'Sed de sangre', categoria: 'Ilusion', desc: 'Por 4 turnos descansar hace daño en vez de curar', efecto: 'bloodthirsty_rest', duracion: 4 },
  { id: 'gravedad_invertida', nombre: 'Gravedad invertida', categoria: 'Ilusion', desc: 'Por 3 turnos la resistencia suma al daño en vez de restarlo', efecto: 'invert_resistance', duracion: 3 },
  { id: 'turno_compartido', nombre: 'Turno compartido', categoria: 'Ilusion', desc: 'Por 2 turnos ambos jugadores deben elegir la misma acción o ninguno puede actuar', efecto: 'shared_turn', duracion: 2 },
  { id: 'dado_de_dios', nombre: 'Dado de dios', categoria: 'Azar', desc: 'Ambos tiran un dado. Multiplican su resultado por 10 y eso es el daño que reciben', efecto: 'god_dice' },
  { id: 'loteria_de_stats', nombre: 'Lotería de stats', categoria: 'Azar', desc: 'Se redistribuyen aleatoriamente todos los puntos de habilidad de ambos jugadores por 5 turnos', efecto: 'stat_lottery', duracion: 5 },
  { id: 'la_moneda', nombre: 'La moneda', categoria: 'Azar', desc: 'Se lanza una moneda. El perdedor pierde la mitad de todos sus stats para siempre', efecto: 'coin_flip' },
  { id: 'numero_bestia', nombre: 'Número de la bestia', categoria: 'Azar', desc: 'Si alguien saca 6 en cualquier dado durante los próximos 3 turnos, recibe 30 de daño instantáneo', efecto: 'beast_number', duracion: 3 },
  { id: 'manos_manteca', nombre: 'Manos de manteca', categoria: 'Farsa', desc: 'Por 3 turnos, cada vez que alguien intente atrapar un objeto lanzado, automáticamente falla', efecto: 'butter_hands', duracion: 3 },
  { id: 'el_torpe', nombre: 'El torpe', categoria: 'Farsa', desc: 'Por 2 turnos, cada acción que hagas tiene 50% de chance de fallar completamente', efecto: 'clumsy', duracion: 2 },
  { id: 'mudez', nombre: 'Mudez', categoria: 'Farsa', desc: 'Por 3 turnos ningún jugador puede negociar ni comunicarse para coordinar nada', efecto: 'mute', duracion: 3 },
  { id: 'el_payaso', nombre: 'El payaso', categoria: 'Farsa', desc: 'El jugador con más velocidad debe desperdiciar su primera acción de cada turno durante 3 turnos', efecto: 'waste_action', duracion: 3 },
  { id: 'ego_destruido', nombre: 'Ego destruido', categoria: 'Farsa', desc: 'El jugador con más fuerza no puede atacar directamente por 2 turnos', efecto: 'no_attack', duracion: 2 },
  { id: 'zona_de_guerra', nombre: 'Zona de guerra', categoria: 'Mundo', desc: 'Permanente: descansar solo recupera 1 HP y 1 energía en vez de 5', efecto: 'war_zone' },
  { id: 'tierra_sagrada', nombre: 'Tierra sagrada', categoria: 'Mundo', desc: 'Por 5 turnos nadie puede morir. Si llegan a 0 HP quedan en 1', efecto: 'sacred_ground', duracion: 5 },
  { id: 'niebla_caos', nombre: 'Niebla del caos', categoria: 'Mundo', desc: 'Por 4 turnos todos los dados se tiran con los ojos cerrados y no se puede ver el resultado del rival', efecto: 'chaos_fog', duracion: 4 },
  { id: 'campo_electrico', nombre: 'Campo eléctrico', categoria: 'Mundo', desc: 'Permanente hasta la próxima fortuna: cada pose fallida hace 8 de daño al que la intentó', efecto: 'electric_field' },
  { id: 'gravedad_extrema', nombre: 'Gravedad extrema', categoria: 'Mundo', desc: 'Permanente: lanzar objetos está prohibido, son demasiado pesados', efecto: 'heavy_gravity' },
  { id: 'clon', nombre: 'Clon', categoria: 'Oculto', desc: 'Aparece un clon de ambos jugadores con la mitad de sus stats que ataca de forma automática cada turno por 3 turnos', efecto: 'clone', duracion: 3 },
  { id: 'el_fantasma', nombre: 'El fantasma', categoria: 'Oculto', desc: 'El jugador con menos HP se vuelve intocable por 2 turnos pero tampoco puede atacar', efecto: 'ghost', duracion: 2 },
  { id: 'amnesia_total', nombre: 'Amnesia total', categoria: 'Oculto', desc: 'Ambos jugadores olvidan sus pasivas y sus stats por 3 turnos. Combaten como personajes nivel 1 con 5 en todo', efecto: 'amnesia', duracion: 3 },
];

module.exports = FORTUNE_CARDS;
